Repository 3dwardch3ng/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#7 fix index yaml
  .github/workflows/release.yml
  .github/workflows/renovate.yaml
  docs/cr.yaml
Labels: skip-version-bump

#8 chore(versions): update dependency versions
  .github/workflows/release.yml
  charts/adguard-home/Chart.yaml
  charts/adguard-home/README.md
  charts/code-server/Chart.yaml
  charts/code-server/README.md
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/homer/Chart.yaml
  charts/homer/README.md
  charts/prometheus/Chart.yaml
  charts/prometheus/README.md
  docs/requirements.txt
Labels: dependencies, patch

#9 update pipeline
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/help_request.yaml
  .github/renovate.json
  .github/workflows/release.yml
  README.md
  charts/adguard-home/Chart.yaml
  charts/adguard-home/README.md
  charts/code-server/Chart.yaml
  charts/code-server/README.md
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/homer/Chart.yaml
  charts/homer/README.md
  charts/prometheus/Chart.yaml
  charts/prometheus/README.md
  docs/docs/artifacthub-repo.yml
  docs/docs/site.webmanifest
  docs/mkdocs.yml
  docs/templates/README.md.gotmpl
Labels: patch

#10 chore(misc): upload GH cache
  .github/workflows/release.yml
Labels: patch

#11 chore(misc): upload GH cache
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/help_request.yaml
  .github/renovate.json
  README.md
  charts/adguard-home/Chart.lock
  charts/adguard-home/Chart.yaml
  charts/adguard-home/README.md
  charts/code-server/Chart.lock
  charts/code-server/Chart.yaml
  charts/code-server/README.md
  charts/grafana/Chart.lock
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/homer/Chart.lock
  charts/homer/Chart.yaml
  charts/homer/README.md
  charts/prometheus/Chart.lock
  charts/prometheus/Chart.yaml
  charts/prometheus/README.md
  docs/docs/artifacthub-repo.yml
  docs/docs/site.webmanifest
  docs/mkdocs.yml
  docs/templates/README.md.gotmpl
Labels: patch

#12 update charts
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/help_request.yaml
  .github/renovate.json
  README.md
  charts/adguard-home/Chart.yaml
  charts/adguard-home/README.md
  charts/code-server/Chart.yaml
  charts/code-server/README.md
  charts/grafana/Chart.yaml
  charts/grafana/README.md
  charts/homer/Chart.yaml
  charts/homer/README.md
  charts/prometheus/Chart.yaml
  charts/prometheus/README.md
  docs/docs/artifacthub-repo.yml
  docs/docs/site.webmanifest
  docs/mkdocs.yml
  docs/templates/README.md.gotmpl
Labels: skip-version-bump

#13 chore(misc): update index
  .github/workflows/release.yml
Labels: skip-version-bump

#14 chore(misc): update index
  .github/workflows/release.yml
Labels: patch

#15 chore(misc): fix yaml format
  .github/workflows/release.yml
Labels: patch

#16 chore(misc): fix index
  charts/adguard-home/Chart.lock
  charts/code-server/Chart.lock
  charts/grafana/Chart.lock
  charts/homer/Chart.lock
  charts/prometheus/Chart.lock
Labels: patch

#17 chore(argocd): server service type to expose ports
  pi-cluster/argocd/values.yaml
Labels: skip-version-bump

#18 chore(prometheus): update service
  README.md
  charts/prometheus/values.yaml
  pi-cluster/prometheus/.helmignore
  pi-cluster/prometheus/Chart.yaml
  pi-cluster/prometheus/README.md
  pi-cluster/prometheus/README_CONFIG.md.gotmpl
  pi-cluster/prometheus/templates/persistentvolume.yaml
  pi-cluster/prometheus/values.yaml
Labels: skip-version-bump

#19 Service/adgardhome update persistence
  pi-cluster/adguard-home/values.yaml
Labels: skip-version-bump
